<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;

#[Signature('bizagi-extension:configure')]
#[Description('Write APP_URL into the Bizagi browser extension so it sends attendance to this app')]
class ConfigureBizagiExtension extends Command
{
    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $appUrl = rtrim((string) config('app.url'), '/');

        if (filter_var($appUrl, FILTER_VALIDATE_URL) === false) {
            $this->components->error("APP_URL is not a valid URL: «{$appUrl}»");

            return self::FAILURE;
        }

        file_put_contents(
            base_path('browser-extension/bizagi-export/config.js'),
            "// Generated by `php artisan bizagi-extension:configure` from APP_URL. Do not edit.\nexport const APP_URL = ".json_encode($appUrl, JSON_UNESCAPED_SLASHES).";\n",
        );

        $this->components->info("The extension now sends to {$appUrl}. Reload it in the browser's extensions page.");

        return self::SUCCESS;
    }
}
